# Backstage documentation
# https://backstage.io/docs/features/software-catalog/descriptor-format/

apiVersion: backstage.io/v1alpha1
# Component, API, Template, Group, User, Resource, System, Domain, Location
kind: Component
metadata:
  name: contentful-persistence.swift 
  description: unknown
  annotations:
    github.com/project-slug: contentful/contentful-persistence.swift 
    contentful.com/service-tier: "4"

  tags:
    #need to add sast.yaml to .github/workflows and enable it in polaris dashboard
    #once that is done this can be changed to sast-enabled
    - sast-disabled
    - tier-4
spec:
  #cli, component, contentful.com/template, documentation, function, library, service, template, website
  type: library 
  #deprecated, experimental, production, unknown
  lifecycle: unknown  
  system: unknown #optional
  # your team name as it appears in github when tagging them for reviews
  owner: group:team-tundra 