apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contentful-persistence.swift 
  description: An integration to simplify persisting data from Contentful to a local CoreData database; built on top of the official Contentful Swift Library.
  annotations:
    github.com/project-slug: contentful/contentful-persistence.swift 
    contentful.com/service-tier: "4"
    contentful.com/ci-alert-slack: prd-ecosystem-dx-bots
  tags:
    - tier-4
spec:
  type: library 
  lifecycle: production  
  owner: group:team-developer-experience 
